[package]
name = "audio-prototype-1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.12"
cpal = "0.15.2"
crossbeam = "0.8"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8.15"
iced = "0.8.0"
iced_aw = { version = "0.4.1", features = ["card", "badge"] }
iced_native = "0.9.1"
